framework:
    mailer:
       dsn: '%env(MAILER_DSN)%'
       message_bus: false
       envelope:
         sender: 'facturoproject@proton.me'
         recipients: [ 'amontour12@gmail.com' ]
#        envelope:
#            sender: 'fabien@example.com'
#            recipients: [ 'foo@example.com', 'bar@example.com' ]
#            headers:
#                    From: 'Fabien <fabien@example.com>'
#                    Bcc: 'baz@example.com'
#                    X-Custom-Header: 'foobar'
